<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="public/css/bootstrap.min.css">
    <link rel="stylesheet" href="public/css/all.min.css">
    <!-- <link rel="stylesheet" href="public/css/font-awesome.min.css"> -->

    <!-- Bootstrap CSS -->
    

    <title>Admin Panel</title>
  </head>
  <body>